orbs:
  node: circleci/node@7.1.0
  jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install-packages
workflows:
  example-workflow:
    jobs:
      - example-job